name: naked_ui
description: A library of behavior-first UI components for Flutter that separate state from presentation.
repository: https://github.com/conceptadev/naked_ui
documentation: https://docs.page/conceptadev/naked_ui
issue_tracker: https://github.com/conceptadev/naked_ui/issues
license: BSD-3-Clause
version: 1.0.0-beta.10
resolution: workspace

environment:
  sdk: ">=3.9.0 <4.0.0"
  flutter: ">=3.41.0"

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  meta: ^1.15.0
  url_launcher_platform_interface: ^2.3.2


flutter:
  uses-material-design: true
